---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - keylime.redhat.com
  resources:
  - attestations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keylime.redhat.com
  resources:
  - attestations/finalizers
  verbs:
  - update
- apiGroups:
  - keylime.redhat.com
  resources:
  - attestations/status
  verbs:
  - get
  - patch
  - update
