apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: osdk-attestation-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Attestation is the Schema for the attestations API
      displayName: Attestation
      kind: Attestation
      name: attestations.keylime.redhat.com
      specDescriptors:
      - description: ListPods allows specifying if the list of pods needs to be retrieved
        displayName: Set to True to list pods
        path: listpods
      statusDescriptors:
      - description: PodList stores the list of pods retrieved
        displayName: List of Pods
        path: podlist
        x-descriptors:
        - urn:alm:descriptor:text
      - description: Version contains the version of the attestation operator
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:text
      version: v1alpha1
  description: Operator SDK based Attestation Operator
  displayName: osdk-attestation-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - attestation
  - security
  links:
  - name: Osdk Attestation Operator
    url: https://osdk-attestation-operator.domain
  maintainers:
  - email: sarroutb@redhat.com
    name: Sergio Arroutbi
  maturity: alpha
  provider:
    name: Red Hat Inc
  version: 0.0.0
